routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
use App\News;

Route::get('/', function () {
    return view('login_v2');
});

//Testing
Auth::routes();
Route::post('/register', 'HomeController@postRegister');

Route::get('/home', 'HomeController@index');

Route::group(array('prefix'=>'administrator'), function(){
    Route::get('/', 'AdminController@getHome');
    Route::get('index', 'AdminController@getHome');
    Route::get('home', 'AdminController@getHome');

    Route::get('news', 'AdminController@getNews');
    Route::post('news/create', 'AdminController@postCreateNews');
    Route::post('news/update', 'AdminController@postUpdateNews');
    Route::post('news/delete', 'AdminController@postDeleteNews');

    Route::get('tours', 'AdminController@getTours');
    Route::get('tours/json', 'AdminController@getToursJson');
    Route::post('tours/create', 'AdminController@postCreateTours');
    Route::post('tours/update', 'AdminController@postUpdateTours');
    Route::post('tours/delete', 'AdminController@postDeleteTours');


    Route::get('promotions', 'AdminController@getPromotions');
    Route::post('promotions/update', 'AdminController@postUpdatePromotions');
    Route::post('promotions/create', 'AdminController@postCreatePromotions');
    Route::post('promotions/delete', 'AdminController@postDeletePromotions');

    Route::get('video', 'AdminController@getVideo');
    Route::post('video/create', 'AdminController@postCreateVideo');

    Route::get('users', 'AdminController@getUsers');
    Route::get('admin', 'AdminController@getAdmin');
});

Route::get('logout', 'AdminController@getLogout');

/*Route::get('/news', 'HomeController@getNews');
Route::post('/news', 'HomeController@postNews');

Route::get('/staff', 'HomeController@getStaff');
Route::post('/staff', 'HomeController@postStaff');

Route::get('/tour','HomeController@getWisataBudaya');
Route::post('/tour','HomeController@postWisataBudaya');*/

Route::get('/token', function(){return csrf_token();});

Route::get('/images/{filename}', function ($filename)
{
    $path = storage_path() . '/app/public/' . $filename;

    if(!File::exists($path)) return abort('404');

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('/images/tours/{filename}', function ($filename)
{
    $path = storage_path() . '/app/tours/' . $filename;

    if(!File::exists($path)) return abort('404');

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('/images/promotions/{filename}', function ($filename)
{
    $path = storage_path() . '/app/promotions/' . $filename;

    if(!File::exists($path)) return abort('404');

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('/images/news/{filename}', function ($filename)
{
    $path = storage_path() . '/app/news/' . $filename;

    if(!File::exists($path)) return abort('404');

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('/images/marker/{filename}', function ($filename)
{
    $path = storage_path() . '/app/marker/' . $filename;

    if(!File::exists($path)) return abort('404');

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('/video/{filename}', function ($filename)
{  
    $path = storage_path() . '/app/video/' . $filename;

    if(!File::exists($path)) return abort('404');

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Auth::routes();

Route::get('/bridge', function() {
    $data = News::first();
    
    $pusher = App::make('pusher');

    $pusher->trigger( 'scantour_event_channel',
                      'data_event', array('title'=>'Pertunjukan Seni Budaya'));

    return "Success";
});

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class News extends Model
{
    protected $table = 'news';

    public function author(){
    	return $this->belongsTo('App\User', 'author_id');
    }

    public function getDateAttribute(){
		if($this->created_at->diffInDays(Carbon::now()) == 0)
    		return $this->created_at->diffForHumans();
    	else
    		return $this->created_at->format('j F Y\\, h:i A');	
		
    }

}

resources/views/admin/detail.blade.php
@extends('layouts.adminLayout')

@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        <i class="fa fa-cube"></i> Detail Usulan
      </h1>
      <ol class="breadcrumb">
        <li><a href="/administrator"><i class="fa fa-dashboard"></i> Home</a></li>
        <li>Usulan</li>
        <li class="active">Detail Usulan</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Info boxes -->
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12 col-lg-12">
          <div class="box box-success">
            <div class="box-body">
                <div class="row">
                  <div class="col-md-4">
                    <h4>Foto</h4>
                    <div class="row" style="padding: 20px;">
                      <div class="col-md-10 col-md-offset-1 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3">
                        @if(is_null($data->foto))
                        <img src="/images/default_usulan.jpg" class="img-responsive">
                        @else
                        <img src="/images/usulan/{{$data->foto}}" class="img-responsive">
                        @endif
                      </div>
                    </div>
                  </div>
                  <div class="col-md-8">
                  <h4>Keterangan</h4>
                    <table class="table table-striped">
                      <tr>
                        <th>Judul</th>
                        <td>{{$data->judul}}</td>
                      </tr>
                      <tr>
                        <th>Kategori</th>
                        <td>{{$data->kategori}}</td>
                      </tr>
                      <tr>
                        <th>Status</th>
                        @if($data->status)
                        <td>Terverifikasi</td>
                        @else
                        <td>Belum terverifikasi</td>
                        @endif
                      </tr>
                      <tr>
                        <th>Jenis Usulan</th>
                        <td>{{$data->jenis}}</td>
                      </tr>
                      <tr>
                        <th>Jenis Inovasi</th>
                        <td>{{$data->inovasi}}</td>
                      </tr>
                    </table>

                    <h4>Pengusul</h4>
                    <table class="table table-striped">
                      <tr>
                        <th>Nama</th>
                        <td>{{$data->nama_lengkap}}</td>
                      </tr>
                      <tr>
                        <th>Identitas</th>
                        <td>{{$data->identitas}}</td>
                      </tr>
                      <tr>
                        <th>No Identitas</th>
                        <td>{{$data->no_identitas}}</td>
                      </tr>
                      <tr>
                        <th>Email</th>
                        <td>{{$data->jenis}}</td>
                      </tr>
                    </table>
                  </div>
                  <!-- col-8 -->
              </div>
              <!-- row -->
              <div class="row">
                <div class="col-md-12">
                  <h4>Kebaharuan</h4>
                  @if($data->kebaharuan->count() > 0)
                  <table class="table table-striped">
                    <?php $c=1; ?>
                    @foreach($data->kebaharuan as $d)
                    <tr>
                      <th>{{$c++}}</th>
                      <th>{{$d->kebaharuan}}</th>
                    </tr>
                    @endforeach
                  </table>
                  @else
                  <strong>Tidak ada kebaharuan</strong>
                  @endif
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->

      
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  @endsection

resources/views/admin/home.blade.php
@extends('adminlte::page')

@section('title', 'Scantour')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <p>You are logged in!</p>
@stop

resources/views/admin/index.blade.php
@extends('layouts.adminLayout')
@section('header')
<style>
  #map {
    height: 400px;
    width: 100%;
   }
</style>
@endsection
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Home
      </h1>
      <ol class="breadcrumb">
        <li><a href="/administrator"><i class="fa fa-home"></i> Home</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Info boxes -->
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-6">
            <div class="info-box bg-yellow">
              <span class="info-box-icon"><i class="fa fa-feed"></i></span>

              <div class="info-box-content">
                <span class='info-box-text'>News</span>
                <span class="info-box-number">{{$data['news']}}</span>
                <span class="progress-description" style="margin-top: 12px;">
                    <a href="/administrator/news" style="text-decorations:none; color:inherit;"><b>See more</b></a>
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
        <!-- /.col -->

          <div class="col-md-3 col-sm-6 col-xs-6">
            <div class="info-box bg-aqua">
              <span class="info-box-icon"><i class="fa fa-map-o"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Tours</span>
                <span class="info-box-number">{{$data['tours']}}</span>
                <span class="progress-description" style="margin-top: 12px;">
                    <a href="/administrator/tours" style="text-decorations:none; color:inherit;"><b>See more</b></a>
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
        <!-- /.col -->
        <!-- fix for small devices only -->
          <div class="clearfix visible-sm-block"></div>

          <div class="col-md-3 col-sm-6 col-xs-6">
            <div class="info-box bg-green">
              <span class="info-box-icon"><i class="fa fa-tag"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Promotions</span>
                <span class="info-box-number">{{$data['promotions']}}</span>
                <span class="progress-description" style="margin-top: 12px;">
                    <a href="/administrator/promotions" style="text-decorations:none; color:inherit;"><b>See more</b></a>
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->

          <div class="col-md-3 col-sm-6 col-xs-6">
            <div class="info-box bg-red">
              <span class="info-box-icon"><i class="fa fa-video-camera  "></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Video</span>
                <span class="info-box-number">{{$data['videos']}}</span>
                <span class="progress-description" style="margin-top: 12px;">
                    <a href="/administrator/video" style="text-decorations:none; color:inherit;"><b>See more</b></a>
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
        <!-- /.col -->
          </div>  
        </div>
        <div class="col-md-8">
          <div class="box box-warning">
            <div class="box-header with-border">
              <h3 class="box-title"><i class="fa fa-map"></i> Tours Map</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
              <div class="row">
                <div class="col-md-12 col-sm-12">
                  <div id="map"></div>
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->
            </div>
            <!-- /.box-body -->
          </div>
        </div>
        <div class="col-md-4">
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"><i class="fa fa-feed"></i> Recently Added News</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <ul class="products-list product-list-in-box">
                @foreach($news as $n)
                <li class="item">
                  <div class="product-img">
                    <img class="img-responsive" src="/images/news/{{$n->image}}" >
                  </div>
                  <div class="product-info">
                    <a href="/administrator/news" class="product-title">{{$n->title}}</a>
                        <span class="product-description">
                          {{$n->date}}
                        </span>
                  </div>
                </li>
                @endforeach
              </ul>
            </div>
            <!-- /.box-body -->
            <div class="box-footer text-center">
              <a href="/administrator/news" class="uppercase">View All News</a>
            </div>
            <!-- /.box-footer -->
          </div>
        </div>
      </div>
      
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  @endsection

  @section('js')
    <script>
      var map;
      var point;

      function initMap() {
        point = {lat: -7.104843, lng: 109.421864};
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 6,
          center: point
        });
        var marker = new google.maps.Marker({
          position: point,
          animation: google.maps.Animation.DROP,
          map: map
        });

        getLocationTours();
      }

      function getLocationTours(){
        $.getJSON('tours/json', function(data) { 
            $.each( data, function(i, value) {

                var myLatlng = new google.maps.LatLng(value.latitude, value.longitude);
                
                var addMarker = new google.maps.Marker({
                  position: myLatlng,
                  map: map,
                  animation: google.maps.Animation.DROP,
                  title: "Title "+value.name
                  });

            });
          });
      }

    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQc7eRbHzd2uo60nlzH_4G2BZqLd5j-xg&callback=initMap">
    </script>
  @endsection

resources/views/admin/news.blade.php
@extends('layouts.adminLayout')
@section('header')
  <link rel="stylesheet" type="text/css" href="/css/dataTables.bootstrap.min.css">
  <style type="text/css">
    .img-view {
      position: relative;
    }
    .img-view button {
      position: absolute;
      top: 5px;
      right: 5px;
      height: 35px;
      width: 35px;
      display: block;
    }
  </style>
@stop
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        News
      </h1>
      <ol class="breadcrumb">
        <li><a href="/administrator/home"><i class="fa fa-home"></i> Home</a></li>
        <li class="active"><a href="/administrator/news">News</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Info boxes -->
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="box box-warning">
            <div class="box-header">
              <i class="fa fa-feed"></i>
              <h3 class="box-title">News</h3>
              <button class="btn btn-sm btn-primary pull-right" data-toggle='modal' data-target="#createNews">Create</button>
            </div>
            <div class="box-body">
              <table class="table table-striped table-bordered dataTable">
                <thead>
                  <tr>
                    <th>No</th>
                    <th>Title</th>
                    <th>Content</th>
                    <th>Date</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                <?php $c=1; ?>
                  @foreach($data as $d)
                  <tr>
                      <td>{{ $c++ }}</td>
                      <td>{{ $d->title }}</td>
                      <td>{{ $d->content }}</td>
                      <td>{{ $d->date}}</td>
                      <td>
                        <a href="#" class="btn btn-xs btn-success detail" data-id='{{$d->id}}' data-title='{{$d->title}}' data-content='{{$d->content}}' data-author='{{$d->author->name}}' data-image="{{$d->image}}" data-created_at="{{$d->date}}"><i class="fa fa-eye"></i></a>
                        <a href="#" class="delete btn btn-xs btn-danger" data-id='{{$d->id}}' data-title='{{$d->title}}'><i class="fa fa-times"></i></a>
                      </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- detail News Modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id='detailNews'>
    <div class="modal-dialog" role="document">
      <form action="/administrator/news/update" method="post" enctype="multipart/form-data">
        <div class="modal-content">
          <div class="modal-header">
            <strong>News Detail</strong><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
          </div>
          <div class="modal-body">
            <div class="col-md-12">
              <div class="col-md-5">
                <div class="img-view">
                  <img src="" id="detailImage" class="img-responsive">
                  <button id="filesTrigger" type='button' class="btn btn-xs btn-info"><i class="fa fa-pencil"></i></button>
                </div>
                
                <br>
              </div>
              <div class="col-md-7">
                <div class="form-group">
                  <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-feed"></i></span>
                    <input type="text" class="form-control" placeholder="Title" id='detailTitle' name="title">
                  </div>
                </div>
                <div class="form-group" style="display: none;">
                  <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-image"></i></span>
                    <input type="file" class="form-control" placeholder="Image" name="image" id="files">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-align-left"></i></span>
                    <textarea class="form-control" name="content" id='detailContent' placeholder="Content"></textarea>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div for='' class="col-sm-6"><i class="fa fa-calendar"></i>  <p style="display:inline" id='detailCreatedAt'>ASDASD</p></div>  
              <div for='' class="col-sm-6 "><i class="fa fa-user"></i> <p style="display:inline" id='detailAuthor'>ASDASD</p></div>  
            </div>
          </div>
          <div class="modal-footer">
              <input type="hidden" name="id" value="" id="detailId">
              {{csrf_field()}}
              <button type="button" class="btn btn-sm" data-dismiss="modal">Cancel</button>
              <button type="submit" class="btn btn-sm btn-primary pull-right">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <div class="modal fade" tabindex="-1" role="dialog" id='createNews'>
    <div class="modal-dialog" role="document">
      <form action="/administrator/news/create" method="post" enctype="multipart/form-data">
        <div class="modal-content">
          <div class="modal-header">
            <strong>Create News</strong><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
          </div>
          <div class="modal-body">
            <div class="col-md-12">
              <div class="form-group">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-feed"></i></span>
                  <input type="text" class="form-control" placeholder="Title" id='createTitle' name="title">
                </div>
              </div>
              <div class="form-group">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-align-left"></i></span>
                  <textarea class="form-control" name="content" id='createContent' placeholder="Content"></textarea>
                </div>
              </div>
              <div class="form-group">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-image"></i></span>
                  <input type="file" class="form-control" placeholder="Image" id='createImage' name="image">
                </div>
              </div>
              <div class="form-group">
                <img src="" id="createImageDetail" class="img-responsive" style="margin-left: auto; margin-right: auto;">
                <br>
              </div>
            </div>
          </div>
          <div class="modal-footer">
              {{csrf_field()}}
              <button type="button" class="btn btn-sm" data-dismiss="modal">Cancel</button>
              <button type="submit" class="btn btn-sm btn-primary pull-right">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>

  @endsection
  @section('js')
    <script src="{{ asset('/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('/js/dataTables.bootstrap.js') }}"></script>
    <script>
      $(document).ready(function() {
        $('.dataTable').dataTable();
      });
    </script>
    <script type="text/javascript">
    $("#filesTrigger").click(function() {
        $("#files").click();
    });
     document.getElementById("files").onchange = function () {
          var reader = new FileReader();

          reader.onload = function (e) {
              // get loaded data and render thumbnail.
               $("#detailImage").fadeOut(1000, function() {
                    document.getElementById("detailImage").src = e.target.result;
                }).fadeIn(1000);
              
          };

          // read the image file as a data URL.
          reader.readAsDataURL(this.files[0]);
      };

      document.getElementById("createImage").onchange = function () {
          var reader = new FileReader();

          reader.onload = function (e) {
              // get loaded data and render thumbnail.
               $("#createImageDetail").fadeOut(1000, function() {
                    document.getElementById("createImageDetail").src = e.target.result;
                }).fadeIn(1000);
              
          };

          // read the image file as a data URL.
          reader.readAsDataURL(this.files[0]);
      };
      
      $('.detail').click(function(){
        var title = $(this).data('title');
        var image = $(this).data('image');
        var content = $(this).data('content');
        var created_at = $(this).data('created_at');
        var author = $(this).data('author');
        var id = $(this).data('id');

        $('#detailTitle').val(title);
        $('#detailContent').val(content);
        $('#detailAuthor').html(author);
        $('#detailCreatedAt').html(created_at);
        $('#detailId').val(id);

        $('#detailImage').attr('src', '/images/news/'+ image);
        $('#detailNews').modal();

      });
      $('.delete').click(function() {
        var id = $(this).data('id');
        var title = $(this).data('title');
        var _token = '{{csrf_token()}}';

        bootbox.confirm("<b>Delete News</b> with this title : <strong>"+title+" </strong> ?", function(result) {
          if (result) {
            toastr.options.timeOut = 0;
            toastr.options.extendedTimeOut = 0;
            toastr.info('<i class="fa fa-spinner fa-spin"></i><br>Process...');
            toastr.options.timeOut = 5000;
            toastr.options.extendedTimeOut = 1000;
            $.post("/administrator/news/delete", {id: id, _token:_token})
            .done(function(result) {
              window.location.replace("/administrator/news/");
            })
            .fail(function(result) {
              toastr.clear();
              toastr.error('Server Error! Please reload this page again.');
            });
          };
        }); 
      });
    </script>
  @stop